INSERT INTO butterflies (
    name, other_names, family, location, habitat, morphology, life, feeding, conservation, about_conservation, image, created_at, updated_at
) VALUES
('Vanesa atalanta', '', 'Nymphalidae (alas cepillo)', 'Presente en España, Francia, Italia, Reino Unido, Alemania, Suecia, Noruega, Finlandia; migraciones hacia el norte en primavera y vuelta al sur en otoño', 'Bosques claros, jardines, márgenes; larvas en ortigas', 'Alas negras con bandas rojas y blancas, envergadura 45–60 mm; forma invernal más oscura', 'Varias generaciones en sur de Europa; hibernación de adultos; huevos en Urtica, larvas espinosas, pupación variable', 'Larvas en ortigas; adultos en néctar, savia, fruta', 'LC; migraciones sensibles al cambio climático', 'LC', 'https://inaturalist-open-data.s3.amazonaws.com/photos/327184069/large.jpeg', NOW(), NOW()),
('Vanesa de los cardos', 'Painted lady', 'Nymphalidae (alas cepillo)', 'España, Portugal, Francia, Reino Unido, Irlanda, Alemania, Italia, Suecia, hasta Islandia; migraciones masivas primavera-otoño', 'Praderas, campos, jardines, bordes semiáridos, montañas', 'Envergadura 51–73 mm; alas naranja con bandas negras y blancas; reverso grisáceo', 'Múltiples generaciones; huevos en Asteraceae; oruga, pupa metálica', 'Larvas en Carduus, Cirsium; adultos en néctar variado', 'LC; migración afectada por clima', 'LC', 'https://www.lavanguardia.com/files/og_thumbnail/uploads/2018/06/13/5fa433c0be305.jpeg', NOW(), NOW()),
('Mariposa del abeto', 'Camberwell beauty', 'Nymphalidae (alas cepillo)', 'España (norte), Francia, Alemania, Suecia, Noruega, Finlandia, Polonia; rara en Reino Unido', 'Bosques caducifolios, ribereños, alamedas', 'Envergadura 60–80 mm; alas marrón oscuro con borde amarillo pálido', 'Generación anual; hibernación de adultos; larvas gregarias', 'Larvas en sauces, álamos, abedules; adultos en savia y fruta podre', 'LC; raro localmente, protegido en algunos países', 'LC', 'https://i.pinimg.com/736x/bd/fa/5a/bdfa5a7d4ee7c10228c0f1b0f707d40e.jpg', NOW(), NOW()),
('Mariposa del ortigal', 'Small tortoiseshell', 'Nymphalidae (alas cepillo)', 'España, Francia, Reino Unido, Irlanda, Alemania, Suecia, Rusia, Polonia', 'Orillas, praderas, jardines con ortigas', 'Anverso naranja con manchas negras/azules, 40–60 mm', '2–3 generaciones; hibernación adulta', 'Larvas en Urtica dioica; adultos en néctar, savia', 'LC, en declive en Reino Unido', 'LC', 'https://upload.wikimedia.org/wikipedia/commons/2/21/Aglais_urticae_LC0310.jpg', NOW(), NOW()),
('Mariposa pavo real', 'Peacock', 'Nymphalidae (alas cepillo)', 'España, Francia, Reino Unido, Irlanda, Alemania, Polonia, Suecia, Rusia', 'Jardines, bosques claros, praderas', 'Alas rojizas con grandes ocelos, 50–55 mm', '2 generaciones (en sur Europa), 1 en norte; hibernación adulta', 'Larvas en ortigas; adultos en néctar, savia, fruta podrida', 'LC; rango estable o en expansión', 'LC', 'https://thumbs.dreamstime.com/b/el-peacock-eye-es-una-mariposa-europea-brillante-con-ojos-manchados-en-las-alas-subfamilia-de-ninfalidos-verdaderos-foto-230687942.jpg', NOW(), NOW()),
('Mariposa del sauce', 'Large tortoiseshell', 'Nymphalidae (alas cepillo)', 'España (Mediterráneo), Francia, Italia, Austria, Eslovenia, Hungría, Rusia; rara en Reino Unido', 'Bosques ribereños con sauces y álamos', 'Alas 60–70 mm, anaranjadas con borde oscuro', 'Una generación anual; hibernación adulta', 'Larvas en Salix, Populus; adultos en savia, fruta', 'LC, pero localmente declinante', 'LC', 'https://us.images.westend61.de/0000345714j/pequena-mariposa-carey-aglais-urticae-sobre-rama-de-sauce-SIEF005233.jpg', NOW(), NOW()),
('Mariposa de los muros', 'Wall brown', 'Nymphalidae (alas cepillo)', 'España, Francia, Reino Unido (sur), Alemania, Polonia, Suecia, Noruega, Grecia', 'Praderas secas, muros, margenes; hasta 3 000 m', 'Envergadura 36–50 mm; anaranjado con ocelo en ala anterior', '2–3 generaciones; orugas hibernan', 'Larvas en gramíneas; adultos en néctar', 'LC', 'LC', 'https://inaturalist-open-data.s3.amazonaws.com/photos/102255693/large.jpg', NOW(), NOW()),
('Mariposa medioluto ibérica', 'Melanargia lachesis', 'Nymphalidae (alas cepillo)', 'España (toda la península), Portugal, sur de Francia (hasta Avignon)', 'Praderas secas y floridas en calizas', 'Alas blancas y ocos negros en cuadrícula, 50–60 mm', 'Una generación (junio–julio); orugas hibernan', 'Larvas en gramíneas; adultos en néctar', 'LC, endémica; sensible a alteraciones de praderas', 'LC', 'https://lh3.googleusercontent.com/proxy/oxowJyFU8N0NHmtAuOdeb3a38Uu3n142j1D0rMkYO6ol52ZnnRzktCj6OBV7Ok62rXkTR9nxre1ux2wqpXNoRPPciMKcQSzaI79r8U_nZTQd', NOW(), NOW()),
('Mariposa medioluto norteña', 'Marbled white', 'Nymphalidae (alas cepillo)', 'España, Francia, Reino Unido, Alemania, Polonia, Rusia, Suecia', 'Praderas secas y claros', 'Alas blancas con manchas negras, 50–56 mm', 'Una generación (junio–agosto); orugas hibernan', 'Larvas en gramíneas; adultos en néctar', 'LC', 'LC', 'https://pictureinsect.com/wiki-image/1080/153984236984991783.jpeg', NOW(), NOW()),
('Mariposa de los prados', 'Meadow brown', 'Nymphalidae (alas cepillo)', 'España, Portugal, Reino Unido, Francia, Alemania, Suecia, Finlandia, Rusia', 'Praderas, bordes herbáceos', 'Envergadura 45–55 mm; alas marrones con ocelos', '1–2 generaciones (dependiendo de latitud); orugas hibernan', 'Larvas en gramíneas; adultos en néctar', 'LC; muy común', 'LC', 'https://i.pinimg.com/736x/6c/23/35/6c2335eed45eaaccddff513eae7efdde.jpg', NOW(), NOW());
